import { LANGS } from "@/lib/seo";

const BASE_URL = "https://residency24.com";

// Sitemap-index file at /sitemap.xml — the canonical entry point most
// crawlers and SEO tools look for. It points to each per-language sitemap
// generated by app/sitemap.ts.
export const revalidate = 3600;

export async function GET() {
  const now = new Date().toISOString();
  const entries = LANGS.map(
    (lang) =>
      `  <sitemap>\n    <loc>${BASE_URL}/sitemap/${lang}.xml</loc>\n    <lastmod>${now}</lastmod>\n  </sitemap>`
  ).join("\n");

  const body = `<?xml version="1.0" encoding="UTF-8"?>\n<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${entries}\n</sitemapindex>\n`;

  return new Response(body, {
    headers: {
      "Content-Type": "application/xml; charset=utf-8",
      "Cache-Control": "public, max-age=3600, s-maxage=3600, stale-while-revalidate=86400",
    },
  });
}
